name: thecodinglove-slack-dev
runtime: yaml
description: Deploys the Slack dev infra (PR builds)

variables:
  location: europe-west1

resources:

  ########################################
  # Pub/Sub (dev)
  ########################################

  # Manages the dev Slack interactivity PubSub topic.
  pubsub-topic-slack-interactivity-dev:
    type: gcp:pubsub:Topic
    properties:
      name: slack_interactivity_dev
    options:
      version: 8.6.0
      protect: true
  # Manages the dev Slack interactivity PubSub subscription.
  pubsub-subscription-slack-interactivity-dev:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_interactivity_dev_subscription
      pushConfig:
        # If this changes, update the tunnel URL in run_local.sh and all other infra/dev Pulumi files too.
        pushEndpoint: https://codinglove.serveousercontent.com/api/pubsub/slack/interactivity
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-interactivity-dev.name}
    options:
      version: 8.6.0
      protect: true
  # Manages the dev Slack slash command PubSub topic.
  pubsub-topic-slack-slash-command-dev:
    type: gcp:pubsub:Topic
    properties:
      name: slack_slash_command_dev
    options:
      version: 8.6.0
      protect: true
  # Manages the dev Slack slash command PubSub subscription.
  pubsub-subscription-slack-slash-command-dev:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_slash_command_dev_subscription
      pushConfig:
        # If this changes, update the tunnel URL in run_local.sh and all other infra/dev Pulumi files too.
        pushEndpoint: https://codinglove.serveousercontent.com/api/pubsub/slack/slash
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-slash-command-dev.name}
    options:
      version: 8.6.0
      protect: true
