name: thecodinglove-slack-dev
runtime: yaml
description: Deploys the Slack dev infra (PR builds)

variables:
  location: europe-west1

resources:

  ########################################
  # Pub/Sub (dev)
  ########################################

  # Manages the dev Slack interactivity received PubSub topic.
  pubsub-topic-slack-interactivity-received-dev:
    type: gcp:pubsub:Topic
    properties:
      name: slack_interactivity_received_dev
    options:
      version: 8.6.0
      protect: true
  # Manages the dev Slack interactivity received PubSub subscription.
  pubsub-subscription-slack-interactivity-received-dev:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_interactivity_received_dev_subscription
      pushConfig:
        # If this changes, update the tunnel URL in run_local.sh and all other infra/dev Pulumi files too.
        pushEndpoint: https://codinglove.serveousercontent.com/api/pubsub/slack/interactivity
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-interactivity-received-dev.name}
    options:
      version: 8.6.0
      protect: true
  # Manages the dev Slack slash command received PubSub topic.
  pubsub-topic-slack-slash-command-received-dev:
    type: gcp:pubsub:Topic
    properties:
      name: slack_slash_command_received_dev
    options:
      version: 8.6.0
      protect: true
  # Manages the dev Slack slash command received PubSub subscription.
  pubsub-subscription-slack-slash-command-received-dev:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_slash_command_received_dev_subscription
      pushConfig:
        # If this changes, update the tunnel URL in run_local.sh and all other infra/dev Pulumi files too.
        pushEndpoint: https://codinglove.serveousercontent.com/api/pubsub/slack/search
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-slash-command-received-dev.name}
    options:
      version: 8.6.0
      protect: true
  # Manages the dev self-destruct message PubSub topic.
  pubsub-topic-slack-self-destruct-message-dev:
    type: gcp:pubsub:Topic
    properties:
      name: slack_self_destruct_message_dev
    options:
      version: 8.6.0
      protect: true
  # Manages the dev self-destruct message PubSub subscription.
  pubsub-subscription-slack-self-destruct-message-dev:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_self_destruct_message_dev_subscription
      pushConfig:
        # If this changes, update the tunnel URL in run_local.sh and all other infra/dev Pulumi files too.
        pushEndpoint: https://codinglove.serveousercontent.com/api/pubsub/self-destruct-message
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-self-destruct-message-dev.name}
    options:
      version: 8.6.0
      protect: true
