name: 'unit-test'
description: 'Run all unit tests'
inputs:
  java-distribution:
    required: true
  java-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup
      uses: ./.github/actions/setup
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
    - name: Test
      shell: bash
      run: |
        set -Eeuo pipefail 
        ./gradlew --no-daemon --continue jsTest
    - name: Generate test report
      uses: mikepenz/action-junit-report@v4
      if: always() # Ensure all test reports are collected, even after errors
      with:
        report_paths: |
          **/TEST-*.xml
        check_name: unit-test-results
    - name: Artifacts
      uses: actions/upload-artifact@v4
      if: always() # Ensure all artifacts are collected, even after errors
      with:
        name: Tests
        path: |
          **/TEST-*.xml