name: thecodinglove-self-destruct
runtime: yaml
description: Deploys the self-destruct infra

variables:
  domain: thecodinglove.crowdstandout.com
  location: europe-west1
  repositoryId: thecodinglove

resources:

  ########################################
  # self-destruct-service
  ########################################

  # Manages the binary.
  self-destruct-service-binary:
    type: docker:Image
    properties:
      build:
        args:
          PORT: "8083"
          API_URL: https://${domain}/api
        platform: linux/amd64
        context: ../service/build/dist/js
      imageName: ${location}-docker.pkg.dev/${gcp:project}/${repositoryId}/self-destruct-service:latest
      registry:
        server: ${location}-docker.pkg.dev
        username: _json_key
        password:
          fn::secret:
            fn::readFile: ${gcp:credentials}
    options:
      protect: true
  # Manages the Cloud Run service.
  self-destruct-service:
    type: gcp:cloudrunv2:Service
    properties:
      ingress: INGRESS_TRAFFIC_ALL
      location: ${location}
      name: self-destruct-service
      template:
        containers:
          - image: ${self-destruct-service-binary.repoDigest}
            ports:
              containerPort: 8083
              name: http1
            resources:
              cpuIdle: true
              limits:
                cpu: 1000m
                memory: 512Mi
            startupProbe:
              failureThreshold: 1
              periodSeconds: 240
              tcpSocket:
                port: 8083
              timeoutSeconds: 240
        maxInstanceRequestConcurrency: 80
        scaling:
          maxInstanceCount: 100
          minInstanceCount: 0
        timeout: 300s
      traffics:
        - percent: 100
          type: TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST
    options:
      version: 8.6.0
      protect: true
  # Manages the Cloud Run service policy.
  self-destruct-service-policy:
    type: gcp:cloudrunv2:ServiceIamPolicy
    properties:
      name: ${self-destruct-service.name}
      location: ${location}
      policyData: |
        {
          "bindings": [
            {
              "role": "roles/run.invoker",
              "members": [
                "allUsers"
              ]
            }
          ]
        }
    options:
      version: 8.6.0
      protect: true

  ########################################
  # Cloud Scheduler
  ########################################

  # Manages the post self-destruct timer.
  self-destruct-timer-job:
    type: gcp:cloudscheduler:Job
    properties:
      name: self-destruct-timer
      schedule: "*/5 * * * *"
      timeZone: Etc/UTC
      region: ${location}
      httpTarget:
        uri: ${self-destruct-service.uri}/api/self-destruct
        httpMethod: GET
      retryConfig:
        retryCount: 5
        maxRetryDuration: 600s
        maxBackoffDuration: 600s
        minBackoffDuration: 10s
        maxDoublings: 5
    options:
      version: 8.6.0
      protect: true

outputs:
  selfDestructServiceHost: ${self-destruct-service.uri}
  selfDestructServicePath: api/self-destruct