name: thecodinglove-slack
runtime: yaml
description: Deploys the Slack infra for TheCodingLove

variables:
  domain: thecodinglove.crowdstandout.com
  location: europe-west1
  repositoryId: thecodinglove

resources:

  ########################################
  # slack-service
  ########################################

  # Manages the binary.
  slack-service-binary:
    type: docker:Image
    properties:
      build:
        args:
          PORT: "8084"
          API_URL: https://${domain}/api
          SLACK_REQUEST_VERIFICATION: "true"
          SLACK_SLASH_COMMAND_PUBSUB_TOPIC: slack_slash_command
          SLACK_INTERACTIVITY_PUBSUB_TOPIC: slack_interactivity
        platform: linux/amd64
        context: ../service/build/dist/js
      imageName: ${location}-docker.pkg.dev/${gcp:project}/${repositoryId}/slack-service:latest
      registry:
        server: ${location}-docker.pkg.dev
        username: _json_key
        password:
          fn::secret:
            fn::readFile: ${gcp:credentials}
    options:
      protect: true
  # Manages the Cloud Run service.
  slack-service:
    type: gcp:cloudrunv2:Service
    properties:
      ingress: INGRESS_TRAFFIC_ALL
      location: ${location}
      name: slack-service
      template:
        containers:
          - image: ${slack-service-binary.repoDigest}
            ports:
              - containerPort: 8084
                name: http1
            resources:
              cpuIdle: true
              limits:
                cpu: 1000m
                memory: 512Mi
            startupProbe:
              failureThreshold: 1
              periodSeconds: 240
              tcpSocket:
                port: 8084
              timeoutSeconds: 240
        maxInstanceRequestConcurrency: 80
        scaling:
          maxInstanceCount: 100
          minInstanceCount: 1
        timeout: 300s
      traffics:
        - percent: 100
          type: TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST
    options:
      protect: true
  # Manages the Cloud Run service policy.
  slack-service-policy:
    type: gcp:cloudrunv2:ServiceIamPolicy
    properties:
      name: ${slack-service.name}
      location: ${location}
      policyData: |
        {
          "bindings": [
            {
              "role": "roles/run.invoker",
              "members": [
                "allUsers"
              ]
            }
          ]
        }
    options:
      protect: true

  ########################################
  # Pub/Sub
  ########################################

  # Manages the Slack interactivity PubSub topic.
  pubsub-topic-slack-interactivity:
    type: gcp:pubsub:Topic
    properties:
      name: slack_interactivity
    options:
      protect: true
  # Manages the Slack interactivity PubSub subscription.
  pubsub-subscription-slack-interactivity:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_interactivity_subscription
      pushConfig:
        pushEndpoint: ${slack-service.uri}/api/pubsub/slack/interactivity
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-interactivity.name}
    options:
      protect: true
  # Manages the dev Slack interactivity PubSub topic.
  pubsub-topic-slack-interactivity-dev:
    type: gcp:pubsub:Topic
    properties:
      name: slack_interactivity_dev
    options:
      protect: true
  # Manages the dev Slack interactivity PubSub subscription.
  pubsub-subscription-slack-interactivity-dev:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_interactivity_dev_subscription
      pushConfig:
        # TODO: Un-hardcode the URL
        pushEndpoint: https://codinglove.serveo.net/api/pubsub/slack/interactivity
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-interactivity-dev.name}
    options:
      protect: true
  # Manages the Slack slash command PubSub topic.
  pubsub-topic-slack-slash-command:
    type: gcp:pubsub:Topic
    properties:
      name: slack_slash_command
    options:
      protect: true
  # Manages the Slack slash command PubSub subscription.
  pubsub-subscription-slack-slash-command:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_slash_command_subscription
      pushConfig:
        pushEndpoint: ${slack-service.uri}/api/pubsub/slack/slash
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-slash-command.name}
    options:
      protect: true
  # Manages the dev Slack slash command PubSub topic.
  pubsub-topic-slack-slash-command-dev:
    type: gcp:pubsub:Topic
    properties:
      name: slack_slash_command_dev
    options:
      protect: true
  # Manages the dev Slack slash command PubSub subscription.
  pubsub-subscription-slack-slash-command-dev:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: slack_slash_command_dev_subscription
      pushConfig:
        # TODO: Un-hardcode the URL
        pushEndpoint: https://codinglove.serveo.net/api/pubsub/slack/slash
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-slack-slash-command-dev.name}
    options:
      protect: true

outputs:
  slackServiceHost: ${slack-service.uri}
  slackServicePath: api/slack
  slackServicePubSubPath: api/pubsub/slack