name: 'infra'
inputs:
  command:
    required: true
  service:
    required: true
  access-token:
    required: true
  infra-dir:
    required: true
  stack-name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up infrastructure
      uses: pulumi/actions@v7
      with:
        command: ${{ inputs.command }}
        stack-name: ${{ inputs.stack-name }}
        work-dir: ${{ inputs.service }}/${{ inputs.infra-dir }}
        edit-pr-comment: false
        pulumi-version: "3.136.1"
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.access-token }}