name: 'build-service'
inputs:
  service:
    required: true
runs:
  using: "composite"
  steps:
    - name: Build service
      shell: bash
      run: |
        set -Eeuo pipefail
        
        if [ -e "${{ inputs.service }}/gradlew" ]; then
          # Need to explicitly cd into each service, otherwise we get concurrent yarn cache clashes
          cd ${{ inputs.service }}
          ./gradlew --no-daemon assemble
          cd ..
        else
          echo "Skipping step as required file doesn't exist"
        fi