services:
  app-service:
    build: ../build/services/app-service/.
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
  statistics-service:
    build: ../build/services/statistics-service/.
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
  landing-page-service:
    build: ../build/services/landing-page-service/.
    ports:
      - "8080:80"
    environment:
      - APP_SERVICE_HOST=http://app-service:8081
      - APP_SERVICE_ROOT=api
      - STATISTICS_SERVICE_HOST=http://statistics-service:8082
      - STATISTICS_SERVICE_ROOT=api/stats