services:
  web-proxy-service:
    build: ../web-proxy/service/build/dist/js
    ports:
      - "8080:80" # host:container
    environment:
      - SEARCH_SERVICE_HOST=http://search-service:8081
      - SEARCH_SERVICE_PATH=api/search
      - SEARCH_SERVICE_PUBSUB_PATH=api/pubsub/search
      - STATISTICS_SERVICE_HOST=http://statistics-service:8082
      - STATISTICS_SERVICE_PATH=api/statistics
      - SELF_DESTRUCT_SERVICE_HOST=http://self-destruct-service:8083
      - SELF_DESTRUCT_SERVICE_PATH=api/self-destruct
      - SLACK_SERVICE_HOST=http://slack-service:8084
      - SLACK_SERVICE_PATH=api/slack
      - SLACK_SERVICE_PUBSUB_PATH=api/pubsub/slack
      - LANDING_PAGE_SERVICE_HOST=http://landing-page-service:8085
  search-service:
    build: ../search/service/build/dist/js
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - API_URL=http://host.docker.internal:8080/api
      - PRELOAD_SEARCH_PUBSUB_TOPIC=preload_search_dev
  statistics-service:
    build: ../statistics/service/build/dist/js
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - API_URL=http://host.docker.internal:8080/api
  self-destruct-service:
    build: ../self-destruct/service/build/dist/js
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - API_URL=http://host.docker.internal:8080/api
  slack-service:
    build: ../slack/service/build/dist/js
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
      - API_URL=http://host.docker.internal:8080/api
      - SLACK_REQUEST_VERIFICATION=true
      - SLACK_SLASH_COMMAND_PUBSUB_TOPIC=slack_slash_command_dev
      - SLACK_INTERACTIVITY_PUBSUB_TOPIC=slack_interactivity_dev
  landing-page-service:
    build: ../landing-page/service/build/dist/js
    ports:
      - "8085:8085"