name: thecodinglove-search
runtime: yaml
description: Deploys the search infra

variables:
  domain: thecodinglove.crowdstandout.com
  location: europe-west1
  repositoryId: thecodinglove

resources:

  ########################################
  # search-service
  ########################################

  # Manages the binary.
  search-service-binary:
    type: docker:Image
    properties:
      build:
        args:
          PORT: "8081"
          API_URL: https://${domain}/api
          PRELOAD_SEARCH_PUBSUB_TOPIC: preload_search
        platform: linux/amd64
        context: ../service/build/dist/js
      imageName: ${location}-docker.pkg.dev/${gcp:project}/${repositoryId}/search-service:latest
      registry:
        server: ${location}-docker.pkg.dev
        username: _json_key
        password:
          fn::secret:
            fn::readFile: ${gcp:credentials}
    options:
      protect: true
  # Manages the Cloud Run service.
  search-service:
    type: gcp:cloudrunv2:Service
    properties:
      ingress: INGRESS_TRAFFIC_ALL
      location: ${location}
      name: search-service
      template:
        containers:
          - image: ${search-service-binary.repoDigest}
            ports:
              - containerPort: 8081
                name: http1
            resources:
              cpuIdle: true
              limits:
                cpu: 1000m
                memory: 512Mi
            startupProbe:
              failureThreshold: 1
              periodSeconds: 240
              tcpSocket:
                port: 8081
              timeoutSeconds: 240
        maxInstanceRequestConcurrency: 80
        scaling:
          maxInstanceCount: 100
          minInstanceCount: 0
        timeout: 300s
      traffics:
        - percent: 100
          type: TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST
    options:
      protect: true
  # Manages the Cloud Run service policy.
  search-service-policy:
    type: gcp:cloudrunv2:ServiceIamPolicy
    properties:
      name: ${search-service.name}
      location: ${location}
      policyData: |
        {
          "bindings": [
            {
              "role": "roles/run.invoker",
              "members": [
                "allUsers"
              ]
            }
          ]
        }
    options:
      protect: true

  ########################################
  # Pub/Sub
  ########################################

  # Manages the preload search PubSub topic.
  pubsub-topic-preload-search:
    type: gcp:pubsub:Topic
    properties:
      name: preload_search
    options:
      protect: true
  # Manages the preload search PubSub subscription.
  pubsub-subscription-preload-search:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: preload_search_subscription
      pushConfig:
        pushEndpoint: ${search-service.uri}/api/pubsub/search
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-preload-search.name}
    options:
      protect: true
  # Manages the dev preload search PubSub topic.
  pubsub-topic-preload-search-dev:
    type: gcp:pubsub:Topic
    properties:
      name: preload_search_dev
    options:
      protect: true
  # Manages the dev preload search PubSub subscription.
  pubsub-subscription-preload-search-dev:
    type: gcp:pubsub:Subscription
    properties:
      ackDeadlineSeconds: 10
      expirationPolicy:
        ttl: ""
      messageRetentionDuration: 600s
      name: preload_search_dev_subscription
      pushConfig:
        # TODO: Un-hardcode the URL
        pushEndpoint: https://codinglove.serveo.net/api/pubsub/search
      retryPolicy:
        maximumBackoff: 600s
        minimumBackoff: 10s
      topic: ${pubsub-topic-preload-search-dev.name}
    options:
      protect: true

outputs:
  searchServiceHost: ${search-service.uri}
  searchServicePath: api/search
  searchServicePubSubPath: api/pubsub/search