services:
  proxy-web-service:
    build: ../../proxy-web/service/build/dist/js
    ports:
      - "8080:80" # host:container
    environment:
      - SEARCH_SERVICE_HOST=http://search-service:8081
      - SEARCH_SERVICE_PATH=api/search
      - SEARCH_SERVICE_PUBSUB_PATH=api/pubsub/search
      - STATISTICS_SERVICE_HOST=http://statistics-service:8082
      - STATISTICS_SERVICE_PATH=api/statistics
      - SELF_DESTRUCT_SERVICE_HOST=http://self-destruct-service:8083
      - SELF_DESTRUCT_SERVICE_PATH=api/self-destruct
      - SLACK_SERVICE_HOST=http://slack-service:8084
      - SLACK_SERVICE_PATH=api/slack
      - SLACK_SERVICE_PUBSUB_PATH=api/pubsub/slack
      - SLACK_WEB_SERVICE_HOST=http://slack-web-service:8086
      - SLACK_WEB_SERVICE_PATH=slack
      - LANDING_PAGE_WEB_SERVICE_HOST=http://landing-page-web-service:80