services:
  search-service:
    build: ../../search/service/build/dist/js
    ports:
      - "8081:8081" # host:container
    environment:
      - PORT=8081
      - API_URL=http://host.docker.internal:8080/api
      - SEARCH_SESSION_RESULT_CREATED_PUBSUB_TOPIC=search_session_result_created_dev