services:
  statistics-service:
    build: ../../statistics/service/build/dist/js
    ports:
      - "8082:8082" # host:container
    environment:
      - PORT=8082
      - API_URL=http://host.docker.internal:8080/api