name: common-deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'common/**'

env:
  JAVA_VERSION: "15"
  JAVA_DISTRIBUTION: "zulu"
  GCP_SA_KEY_INFRA: ${{ secrets.GCP_SA_KEY_INFRA }}
  GCP_SA_KEY_APP: ${{ secrets.GCP_SA_KEY_APP }}
  MONITORING_SLACK_URL: ${{ secrets.MONITORING_SLACK_URL }}

jobs:
  common-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}-common-deploy
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3 # By default, cache is only saved on the 'master' branch
      - name: Set up secrets
        run: |
          echo "$GCP_SA_KEY_INFRA" >> ./common/infra/credentials-gcp-infra.json
          echo "$GCP_SA_KEY_APP" >> ./credentials-gcp-app.json
          echo MONITORING_SLACK_URL="$MONITORING_SLACK_URL" >> ./common/monitoring/secrets.properties
      - name: Build project
        run: |
          set -o pipefail && 
          cd common &&
          ./gradlew --no-daemon assemble &&
          cd ..
      - name: Deploy infrastructure
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: prod
          work-dir: common/infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Ensure all artifacts are collected, even after errors
        with:
          name: Build
          path: |
            **/build
            **/secrets.properties
            common/infra

  common-test:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}-common-test
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3 # By default, cache is only saved on the 'master' branch
      - name: Set up secrets
        run: |
          echo "$GCP_SA_KEY_INFRA" >> ./common/infra/credentials-gcp-infra.json
          echo "$GCP_SA_KEY_APP" >> ./credentials-gcp-app.json
          echo MONITORING_SLACK_URL="$MONITORING_SLACK_URL" >> ./common/monitoring/secrets.properties
      - name: Test
        run: |
          set -o pipefail && 
          cd common &&
          ./gradlew --no-daemon --continue jsTest &&
          cd ..
      - name: Generate test report
        uses: mikepenz/action-junit-report@v4
        if: always() # Ensure all test reports are collected, even after errors
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          check_name: 'common-test-results'
      - name: Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Ensure all artifacts are collected, even after errors
        with:
          name: Tests
          path: '**/build/test-results/**/TEST-*.xml'