name: Deploy Build

on:
  push:
    branches: [ master ]

env:
  JAVA_VERSION: "15"
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  FIREBASE_GCM_SENDER_ID: ${{ secrets.FIREBASE_GCM_SENDER_ID }}
  FIREBASE_APPLICATION_ID: ${{ secrets.FIREBASE_APPLICATION_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}

jobs:
  jsDeploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}_jsDeploy
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: KMP cache
        uses: actions/cache@v3
        id: konan-js-deploy
        with:
          path: '~/.konan/**'
          key: konan-js-deploy
      - name: Compile Javascript app
        run: |
          set -o pipefail && bash ./scripts/env.sh && bash ./scripts/build.sh
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -f
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Javascript deploy
          path: |
            build/productionBackend/*.json
            build/productionBackend/*.ts
            build/productionBackend/*.js
            build/productionBackend/*.map
            build/productionWeb
            firebase-debug.log*
            firebase-debug.*.log
            local.properties

  jsTest:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}_jsTest
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: KMP cache
        uses: actions/cache@v3
        id: konan-js-test
        with:
          path: '~/.konan/**'
          key: konan-js-test
      - name: Javascript tests
        run: |
          set -o pipefail && bash ./scripts/env.sh && ./gradlew --continue jsNodeTest
      # Always run this job even if the previous steps fail to collect all test reports
      - name: Generate Javascript test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          check_name: 'jsTestResults'
      # Always run this job even if the previous steps fail to collect all artifacts
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Javascript test results
          path: '**/build/test-results/**/TEST-*.xml'