name: nightly-check

on:
  pull_request:
    branches: [ master ]

env:
  JAVA_VERSION: "15"
  JAVA_DISTRIBUTION: "zulu"
  PULUMI_VERSION: "3.136.1"
  GCP_SA_KEY_INFRA: ${{ secrets.GCP_SA_KEY_INFRA }}
  GCP_SA_KEY_APP: ${{ secrets.GCP_SA_KEY_APP }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
  SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
  MONITORING_SLACK_URL: ${{ secrets.MONITORING_SLACK_URL }}
  GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}
  GOOGLE_ANALYTICS_API_SECRET: ${{ secrets.GOOGLE_ANALYTICS_API_SECRET }}

jobs:
  check-build:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-check-build
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3 # By default, cache is only saved on the 'master' branch
      - name: Set up secrets
        run: |
          set -Eeuo pipefail
          bash tools/scripts/secrets.sh
      - name: Build services
        run: |
          set -Eeuo pipefail
          ./gradlew --no-daemon assemble
      - name: Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Ensure all artifacts are collected, even after errors
        with:
          name: Build
          path: |
            **/build
            **/secrets.properties
            **/infra
      - name: Slack report
        uses: slackapi/slack-github-action@v1.27.0
        if: always() # Ensure report is always sent, even after errors
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "⚠️️Nightly job <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>|${{ job.name }} failed>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.MONITORING_SLACK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  check-test:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.ref }}-check-test
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3 # By default, cache is only saved on the 'master' branch
      - name: Set up secrets
        run: |
          set -Eeuo pipefail 
          bash tools/scripts/secrets.sh
      - name: Test
        run: |
          set -Eeuo pipefail 
          ./gradlew --no-daemon --continue jsTest
      - name: Generate test report
        uses: mikepenz/action-junit-report@v4
        if: always() # Ensure all test reports are collected, even after errors
        with:
          report_paths: |
            **/TEST-*.xml
          check_name: check-test-results
      - name: Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Ensure all artifacts are collected, even after errors
        with:
          name: Tests
          path: |
            **/TEST-*.xml
      - name: Slack report
        uses: slackapi/slack-github-action@v1.27.0
        if: always() # Ensure report is always sent, even after errors
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "⚠️️Nightly job <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>|${{ job.name }} failed>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.MONITORING_SLACK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK