name: Get Root Directories of Changed Files

on:
  pull_request:
    branches: [ master ]

jobs:
  get-root-directories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Root Directories
        run: |
          git diff --name-only origin/master