name: Get Root Directories of Changed Files

on:
  pull_request:
    branches: [ master ]

jobs:
  get-root-directories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Root Directories
        run: |
          git diff --name-only origin/master | while IFS= read -r file; do [[ -d "${file%%/*}" ]] && echo "${file%%/*}"; done | sort | uniq