name: 'unit-test-composite-action'
description: 'Run all unit tests'

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3 # By default, cache is only saved on the 'master' branch
    - name: Set up secrets
      run: |
        set -Eeuo pipefail 
        bash tools/scripts/secrets.sh
    - name: Test
      run: |
        set -Eeuo pipefail 
        ./gradlew --no-daemon --continue jsTest
    - name: Generate test report
      uses: mikepenz/action-junit-report@v4
      if: always() # Ensure all test reports are collected, even after errors
      with:
        report_paths: |
          **/TEST-*.xml
        check_name: test-results
    - name: Artifacts
      uses: actions/upload-artifact@v4
      if: always() # Ensure all artifacts are collected, even after errors
      with:
        name: Tests
        path: |
          **/TEST-*.xml